# Generated by Django 2.0.1 on 2018-07-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_app', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='osType',
            field=models.CharField(default='android', max_length=10),
        ),
    ]
