# Generated by Django 2.0.1 on 2018-07-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_app', '0007_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='id',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='thumbnail_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='bytes_list',
            field=models.TextField(verbose_name='DESCRIPTION'),
        ),
    ]
