# Generated by Django 2.0.1 on 2018-07-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_app', '0008_auto_20180714_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='img',
            field=models.ImageField(default='my.png', upload_to=''),
        ),
    ]
