# Generated by Django 2.0.1 on 2018-07-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_app', '0009_thumbnail_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='img',
            field=models.ImageField(default='./my.png', upload_to=''),
        ),
    ]
