# Generated by Django 2.0.1 on 2018-07-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_app', '0010_auto_20180716_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='img',
            field=models.ImageField(default='./my.png', upload_to='media'),
        ),
    ]
