# Generated by Django 2.0.1 on 2018-07-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_app', '0012_auto_20180724_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='img',
            field=models.ImageField(default='./my.png', upload_to=''),
        ),
    ]
