# Generated by Django 2.0.1 on 2018-07-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_app', '0013_auto_20180724_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='video',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
