# Generated by Django 2.0.1 on 2018-09-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex1_app', '0017_auto_20180911_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
